### ISSUE TITLE
LNDST dataset

### ISSUE THREAD

**Issue by Mingliang-Liu** [nimishsantosh107/LNDST#1]
The LNDST dataset download link on the competition website is not working, can you provide a copy of the dataset download link? Google Cloud Drive or Amazon Cloud，thx

**Comment by nimishsantosh107** [comment]
Hello, I was using a publicly available dataset from AIcrowd (https://www.aicrowd.com/challenges/ai-for-good-ai-blitz-3/problems/lndst), a company I used to work at. Since I don't work there anymore, it would be best to reach out to their team on discord or email. The website should have their contacts. They should be able to fix that for you.
Have a nice day.
